# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OutilsMTQ
                                 A QGIS plugin
 Regroupe les outils pratiques
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-23
        copyright            : (C) 2021 by Xavier Bourbeau
        email                : xavier.bourbeau@transports.gouv.qc.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from .Parametre import Parametre
from .ParametreAction import ParametreAction

class GestionParametre:
    """
    Objet qui contient les références des parmètres du plugin pour aller les charcher 
    dans les settings de l'utilisateur de QGIS.
    """

    __slots__ = ("dict_parametre", "dict_actions")

    def __init__ (self, dict_parametre:dict[str, Parametre], dict_actions:dict[str, ParametreAction]):
        """
        Constructeur de l'objet GestionParametre

        Args:
            - dict_parametre = Dictionnaire des références aux paramètres du plugin
            - dict_actions = Dictionnaire des références aux action du plugin
        """
        # Dictionnaire des références des parmètres du plugin dans QGIS
        self.dict_parametre = dict_parametre
        # Dictionnaire des objets action de la barre d'outils du plugin
        self.dict_actions = dict_actions
    
    def get(self, name:str)->Parametre:
        """ Permer de retourner l'objet Parametre pour un paramètre du plugin """
        if name in self.dict_parametre: return self.dict_parametre[name]
    
    def getValue(self, name:str, defaut=False):
        """ Permet de retourner la valeur d'un paramètre du plugin enregistrer dans QGIS """
        param = self.get(name)
        if not param: return None
        
        if defaut: return param.getDefaultValue()
        else: return param.get()

    def getDefaultValue(self, name:str):
        """ Permet de retourner la valeur par défault d'un paramètre du plugin enregistrer dans QGIS """
        return self.getValue(name, defaut=True)

    def getAction(self, name:str)->ParametreAction:
        """ Permer de retourner l'objet ParametreAction pour un QAction du plugin """
        if name in self.dict_actions: return self.dict_actions[name]
    
    def getActionsInGroupe(self, groupe:str, only_visible=True):
        """ Permet de retourner une liste des noms des Actions d'un même groupe """
        return [name for name, act in self.dict_actions.items() if act.getGroupe() == groupe and (only_visible and act.get())]

    def setValue(self, name:str, value):
        """ Permet de définir la valeur d'un paramètre du plugin dans QGIS """
        param = self.get(name)
        if param: return param.set(value)
    
