# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OutilsMTQ
                                 A QGIS plugin
 Regroupe les outils pratiques
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-23
        copyright            : (C) 2021 by Xavier Bourbeau
        email                : xavier.bourbeau@transports.gouv.qc.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
from qgis.PyQt.QtGui import QFont
from ..mtq.plugin_setting.Parametre import Parametre
from ..mtq.plugin_setting.ParametreAction import ParametreAction
from ..mtq.plugin_setting.ParametreInt import ParametreInt
from ..mtq.plugin_setting.ParametreBool import ParametreBool
from ..mtq.plugin_setting.ParametreFont import ParametreFont
from ..mtq.plugin_setting.GestionParametre import GestionParametre

class PluginParametres(GestionParametre):
    """
    Objet qui contient les références des parmètres du plugin pour aller les charger
    dans les settings de l'utilisateur de QGIS.
    """

    def __init__ (self):
        # Composant de l'emplacement dans QGIS des Settings
        plugin_name = "PluginChainageMTQ"
        categorie_layers = "Layers"
        categorie_option = "Option"
        categorie_config = "Config"
        
        # Emplacement du dossier du plugin
        self.plugin_dir = os.path.dirname(os.path.dirname(__file__))
        # Définir les chemins par défault à l'interieur du plugin
        path_to_default_style_eccusson = os.path.realpath(os.path.join(self.plugin_dir, 'styles\styles_ecusson.qml'))
        path_to_eccusson_backgroud = os.path.realpath(os.path.join(self.plugin_dir, 'styles'))
        path_to_default_style_atlas = os.path.realpath(os.path.join(self.plugin_dir, 'styles\styles_atlas.qml'))
        path_to_default_style_chainage = os.path.realpath(os.path.join(self.plugin_dir, 'styles\point_de_chainage.qml'))
        path_to_default_style_transect = os.path.realpath(os.path.join(self.plugin_dir, 'styles\styles_transect.qml'))
        # Définir la valueur de police par défault 
        text_on_map_font = QFont()
        text_on_map_font.setPointSize(9)
        text_on_map_font.setItalic(True)
        
        # ========================= Définir les paramètres par défault ===============================
        dict_parametre:dict[str, Parametre] = {
            # Paramètre: Nom du layer RTSS
            "layer_rtss": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="layer_rtss",
                default_value="BGR - RTSS"),
            # Paramètre: Nom du champs du numéro de RTSS
            "field_num_rtss": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_num_rtss",
                default_value="num_rts"),
            # Paramètre: Nom du champs de chainage de début
            "field_chainage_debut": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_chainage_debut",
                default_value="chang_debut"),
            # Paramètre: Nom du champs de chainage de fin
            "field_chainage_fin": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_chainage_fin",
                default_value="val_longr_sous_route"),
            # Paramètre: Nom du champs de classification
            "field_classification": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_classification",
                default_value="cod_clasf_fonct"),
            # Paramètre: Précision du chainage à utiliser
            "precision_chainage": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="precision_chainage",
                default_value=0),
            # Paramètre: Utiliser le formatage des RTSS 
            "formater_rtss": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="formater_rtss",
                default_value=True),
            # Paramètre: Utiliser le formatage des chainage
            "formater_chainage": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="formater_chainage",
                default_value=True),
            # Paramètre: Utiliser seulement les RTSS visible dans la symbologie de la couche
            "use_only_on_visible": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="use_only_on_visible",
                default_value=False),
            # Paramètre: Police d'écriture des tooltip
            "font_on_map": ParametreFont(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="font_on_map",
                default_value=text_on_map_font),
            # Paramètre: Couleur du texte des tooltip
            "color_font_on_map": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="color_font_on_map",
                default_value="#000000"),
            # Paramètre: Afficher le numéro du RTSS dans le tooltip
            "show_rtss_on_map": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_rtss_on_map",
                default_value=False),
            # Paramètre: Afficher le chainage dans le tooltip
            "show_chainage_on_map": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_chainage_on_map",
                default_value=True),
            # Paramètre: Afficher la distance dans le tooltip
            "show_distance_on_map": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_distance_on_map",
                default_value=False),
            # Paramètre: Afficher la valeur de context dans le tooltip
            "show_context_on_map": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_context_on_map",
                default_value=False),
            # Paramètre: Dernière position de la fenêtre d'ajout d'entité 
            "dlg_add_feat_last_pos": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="dlg_add_feat_last_pos",
                default_value=2),
            # Paramètre: Utiliser un raccourcis clavier pour le suivi du chainage
            "use_raccourcis_chainage": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="use_raccourcis_chainage",
                default_value=True),
            # Paramètre: Raccourci clavier du suivi de chainage
            "raccourcis_clavier": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="raccourcis_clavier",
                default_value='C'),
            # Paramètre: Utiliser un raccourcis clavier pour le placement d'écusson
            "use_raccourcis_ecusson": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="use_raccourcis_ecusson",
                default_value=False),
            # Paramètre: Raccourci clavier du placement d'écusson
            "raccourcis_clavier_ecusson": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="raccourcis_clavier_ecusson",
                default_value='E'),
            # Paramètre: Nom de la couche des écussons
            "layer_ecusson_name": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_ecusson_name",
                default_value='Écussons'),
            # Paramètre: Nom du champs du numéro de route
            "layer_ecusson_field_route": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_ecusson_field_route",
                default_value='route'),
            # Paramètre: Nom du champs de la classification fonctionnelle
            "layer_ecusson_field_classe": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_ecusson_field_classe",
                default_value='classe'),
            # Paramètre: Chemin vers le fichier qml de style pour la couche des écussons
            "layer_ecusson_style": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_ecusson_style",
                default_value=path_to_default_style_eccusson),
            # Paramètre: Chemin vers le fichier qml de style pour la couche des page d'atlas
            "layer_atlas_style": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_atlas_style",
                default_value=path_to_default_style_atlas),
            # Paramètre: Utiliser un raccourcis clavier pour la mesure de distance
            "use_raccourcis_distance": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="use_raccourcis_distance",
                default_value=False),
            # Paramètre: Raccourci clavier pour la mesure de distance
            "raccourcis_clavier_distance": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="raccourcis_clavier_distance",
                default_value='D'),
            # Paramètre: Chemin vers les écussons vide par défault
            "ecusson_path": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="ecusson_path",
                default_value=path_to_eccusson_backgroud),
            # Paramètre: Chemin vers le fichier qml de style pour la couche des points de chainage
            "layer_chainage_style": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_chainage_style",
                default_value=path_to_default_style_chainage),
            # Paramètre: Chemin vers le fichier qml de style pour la couche des transects
            "layer_transect_style": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="layer_transect_style",
                default_value=path_to_default_style_transect),
            # Paramètre: Suivre les mise à jour du plugin
            "suivi_plugin_update": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="suivi_plugin_update",
                default_value=True),
            # Paramètre: Couleur de la ligne de mesure
            "mesure_line_color": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="mesure_line_color",
                default_value="#e4741e"),
            # Paramètre: Garder le marqueur de suivi du chainage sur la carte
            "keep_marker_suivi_chainage": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="keep_marker_suivi_chainage",
                default_value=False),
            # Paramètre: Précision utilisé pour de l'outil de mesure
            "precision_mesure": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="precision_mesure",
                default_value=1),
            # Paramètre: Précision utilisé pour la distance du RTSS afficher sur la carte
            "precision_distance": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="precision_distance",
                default_value=1),
            # Paramètre: Raccourci clavier pour l'accrochage parralèle de numérisation
            "raccourcis_clavier_parralele": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="raccourcis_clavier_parralele",
                default_value='P'),
            # Paramètre: Raccourci clavier pour l'accrochage perpendiculaire de numérisation
            "raccourcis_clavier_perpendiculaire": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="raccourcis_clavier_perpendiculaire",
                default_value='O'),
            # Paramètre: Affichier les options de copies des informations générale dans le menu
            "show_copie_menu_info": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_copie_menu_info",
                default_value=True),
            # Paramètre: Affichier les options de copies des valeurs non-formater dans le menu
            "show_copie_menu_non_formater": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_copie_menu_non_formater",
                default_value=True),
            # Paramètre: Affichier les options de copies des valeurs formater dans le menu
            "show_copie_menu_formater": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="show_copie_menu_formater",
                default_value=True),
            # Paramètre: Permet de dire si le marqueur devrait être a la position exacte ou au chainage arrondi
            "pos_marqueur_arrondi": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="pos_marqueur_arrondi",
                default_value=True),
            # Paramètre: Nom de la couche de context
            "context_layer": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="context_layer",
                default_value=""),
            # Paramètre: Nom du champ du numéro de route dans la couche de context
            "field_context_route": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_context_route",
                default_value=""),
            # Paramètre: Nom du champ de valeur dans la couche de context
            "field_context_value": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_layers,
                setting_name="field_context_value",
                default_value=""),
            # Paramètre: Distance des intervalle de point pour l'interpolation de la couche lors de l'analyse du réseau segmenté
            "intervalle_interpolation": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="intervalle_interpolation",
                default_value=20),
            # Paramètre: Distance maximal pour l'interpolation de la couche lors de l'analyse du réseau segmenté
            "dist_interpolation": ParametreInt(
                plugin_name=plugin_name,
                categorie=categorie_option,
                setting_name="dist_interpolation",
                default_value=10),
            # Paramètre: Charger les expressions personaliser du plugin
            "load_custom_expressions": ParametreBool(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="load_custom_expressions",
                default_value=True),
            # Paramètre: Chemin vers le répertoire des fichier ZIP des versions du plugin
            "dossier_plugin_update": Parametre(
                plugin_name=plugin_name,
                categorie=categorie_config,
                setting_name="dossier_plugin_update",
                default_value=r"//sstao00-adm005/TridentAnalyst/Plugin_chainage_mtq/Plugin")}
        
        # =================== Définir les action du plugin =================
        # Dictionnaire des objets action de la barre d'outils du plugin
        dict_actions:dict[str,ParametreAction] = {
            "Paramètre": ParametreAction(
                plugin_name=plugin_name,
                nom="Paramètre",
                icon=self.setIcon("Parametres.png"),
                setting_name="parametre_is_visible",
                visible_by_default=True),

            "Suivre le chainage": ParametreAction(
                plugin_name=plugin_name,
                nom="Suivre le chainage",
                icon=self.setIcon("chaine.png"),
                setting_name="suivre_chainage_is_visible",
                visible_by_default=True),

            "Mesurer un chainage": ParametreAction(
                plugin_name=plugin_name,
                nom="Mesurer un chainage",
                icon=self.setIcon("mesure.png"),
                setting_name="mesurer_is_visible",
                visible_by_default=True),

            "Calculer un interval de chainage": ParametreAction(
                plugin_name=plugin_name,
                nom="Calculer un interval de chainage",
                icon=self.setIcon("chainage.png"),
                setting_name="interval_chainage_is_visible",
                visible_by_default=True,
                groupe="intervalle"),

            "Calculer des transects": ParametreAction(
                plugin_name=plugin_name,
                nom="Calculer des transects",
                icon=self.setIcon("transect.png"),
                setting_name="transects_is_visible",
                visible_by_default=True,
                groupe="intervalle"),

            "Calculer des atlas": ParametreAction(
                plugin_name=plugin_name,
                nom="Calculer des atlas",
                icon=self.setIcon("atlas.png"),
                setting_name="atlas_is_visible",
                visible_by_default=True,
                groupe="intervalle"),

            "Placer des écussons": ParametreAction(
                plugin_name=plugin_name,
                nom="Placer des écussons",
                icon=self.setIcon("ecusson.png"),
                setting_name="placer_ecusson_is_visible",
                visible_by_default=True),

            "Creation de geometrie": ParametreAction(
                plugin_name=plugin_name,
                nom="Creation de geometrie",
                icon=self.setIcon("create_line.png"),
                setting_name="creer_geometrie_is_visible",
                visible_by_default=True),

            "Open SIGO": ParametreAction(
                plugin_name=plugin_name,
                nom="Open SIGO",
                icon=self.setIcon("igo.png"),
                setting_name="open_sigo_is_visible",
                visible_by_default=True),

            "Open SVN": ParametreAction(
                plugin_name=plugin_name,
                nom="Open SVN",
                icon=self.setIcon("svn.png"),
                setting_name="open_svn_is_visible",
                visible_by_default=False),
            
            "Open SVN 360": ParametreAction(
                plugin_name=plugin_name,
                nom="Open SVN 360",
                icon=self.setIcon("svn_360.png"),
                setting_name="open_svn_360_is_visible",
                visible_by_default=False),
            
            "Geocodage inverse": ParametreAction(
                plugin_name=plugin_name,
                nom="Geocodage inverse",
                icon=self.setIcon("geocodage_inverse.png"),
                setting_name="geocodage_inverse_is_visible",
                visible_by_default=False),

            "Aide": ParametreAction(
                plugin_name=plugin_name,
                nom="Aide",
                icon=self.setIcon("help.png"),
                setting_name="help_is_visible",
                visible_by_default=True),
            }
    
        GestionParametre.__init__(self, dict_parametre=dict_parametre, dict_actions=dict_actions)


    def setIcon(self, icon_name):
        return os.path.join(self.plugin_dir, f"icons/{icon_name}")
    
    def showContextMenu(self):
        """ Permet de verifier si un menu pour les options de copier doit être ajouté """
        return any([
            self.getValue("show_copie_menu_info"),
            self.getValue("show_copie_menu_non_formater"),
            self.getValue("show_copie_menu_formater")])
        

    
