# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OutilsMTQDockWidget
                                 A QGIS plugin
 Regroupe les outils pratiques
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Xavier Bourbeau
        email                : xavier.bourbeau@transports.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

# Class pour la gestion des paramètre du plugin
from ..gestion_parametres import sourceParametre


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'fenetre_transect.ui'))


class fenetreTransect(QtWidgets.QDialog, FORM_CLASS):

    closing_window = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(fenetreTransect, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        self.gestion_parametre = sourceParametre()
        precision = self.gestion_parametre.getParam("precision_chainage").getValue()
        single_step = 10
        if precision < 0: single_step = single_step ** abs(precision)
        minimum = 10 ** (precision * -1)
        
        self.spx_intervalle.setDecimals(precision)
        self.spx_intervalle.setSingleStep(single_step)
        self.spx_intervalle.setMinimum(minimum)

    def closeEvent(self, event):
        self.closing_window.emit()
        event.accept()
